version: "3"

services:

  nginx:
    image: nginx:1.17.10
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /srv/docker/picsou/logs:/var/log/nginx/
    ports:
      - 10132:80
    depends_on:
      - frontend
      - backend

  backend:
    restart: unless-stopped
    image: picsou/backend:devel
    tty: true
    build: 
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
        - ./backend:/app
        - /srv/docker/picsou/logs:/logs

  frontend:
      image: picsou/frontend:devel
      stdin_open: true
      build:
          context: frontend
          dockerfile: Dockerfile
      volumes:
          - ./frontend/app:/app
      environment:
          NODE_ENV: development
          CHOKIDAR_USEPOLLING: "true"
          REACT_APP_API_KEY: ${REACT_APP_API_KEY}
          REACT_APP_AUTH_DOMAIN: ${REACT_APP_AUTH_DOMAIN}
          REACT_APP_PROJECT_ID: ${REACT_APP_PROJECT_ID}
          REACT_APP_STORAGE_BUCKET: ${REACT_APP_STORAGE_BUCKET}
          REACT_APP_MESSAGING_SENDER_ID: ${REACT_APP_MESSAGING_SENDER_ID}
          REACT_APP_APP_ID: ${REACT_APP_APP_ID}
  


  
    